"""create booking table

Revision ID: 82ab74f3a6f1
Revises: 95ae072fcbe1
Create Date: 2026-09-30 18:48:51.446712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82ab74f3a6f1'
down_revision: Union[str, Sequence[str], None] = '95ae072fcbe1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('bookingid', sa.Integer(), nullable=False),
    sa.Column('contact_number', sa.String(), nullable=False),
    sa.Column('emailid', sa.String(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ),
    sa.PrimaryKeyConstraint('bookingid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookings')
    # ### end Alembic commands ###
