"""create all car models

Revision ID: 95ae072fcbe1
Revises: 5f113557729a
Create Date: 2026-09-30 18:31:23.727451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95ae072fcbe1'
down_revision: Union[str, Sequence[str], None] = '5f113557729a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fuel_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fueltype', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gear_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('geartype', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('cars', sa.Column('colour', sa.String(), nullable=False))
    op.add_column('cars', sa.Column('year', sa.Integer(), nullable=False))
    op.add_column('cars', sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('cars', sa.Column('carlocation', sa.String(), nullable=False))
    op.add_column('cars', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.add_column('cars', sa.Column('brand_id', sa.Integer(), nullable=False))
    op.add_column('cars', sa.Column('fueltype_id', sa.Integer(), nullable=False))
    op.add_column('cars', sa.Column('geartype_id', sa.Integer(), nullable=False))
    op.add_column('cars', sa.Column('post_status_id', sa.Integer(), nullable=False))
    op.add_column('cars', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_foreign_key(None, 'cars', 'brands', ['brand_id'], ['id'])
    op.create_foreign_key(None, 'cars', 'fuel_types', ['fueltype_id'], ['id'])
    op.create_foreign_key(None, 'cars', 'gear_types', ['geartype_id'], ['id'])
    op.create_foreign_key(None, 'cars', 'users', ['owner_id'], ['id'])
    op.create_foreign_key(None, 'cars', 'post_status', ['post_status_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cars', type_='foreignkey')
    op.drop_constraint(None, 'cars', type_='foreignkey')
    op.drop_constraint(None, 'cars', type_='foreignkey')
    op.drop_constraint(None, 'cars', type_='foreignkey')
    op.drop_constraint(None, 'cars', type_='foreignkey')
    op.drop_column('cars', 'created_at')
    op.drop_column('cars', 'post_status_id')
    op.drop_column('cars', 'geartype_id')
    op.drop_column('cars', 'fueltype_id')
    op.drop_column('cars', 'brand_id')
    op.drop_column('cars', 'owner_id')
    op.drop_column('cars', 'carlocation')
    op.drop_column('cars', 'price')
    op.drop_column('cars', 'year')
    op.drop_column('cars', 'colour')
    op.drop_table('users')
    op.drop_table('post_status')
    op.drop_table('gear_types')
    op.drop_table('fuel_types')
    op.drop_table('brands')
    # ### end Alembic commands ###
