"""create booking add coloumns

Revision ID: 9ef8866711d2
Revises: 82ab74f3a6f1
Create Date: 2026-09-30 18:57:18.862766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ef8866711d2'
down_revision: Union[str, Sequence[str], None] = '82ab74f3a6f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('name', sa.String(), nullable=False))
    op.add_column('users', sa.Column('contact_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'contact_number')
    op.drop_column('bookings', 'name')
    # ### end Alembic commands ###
