"""create booking add edit connections

Revision ID: cf1d068f9667
Revises: 9ef8866711d2
Create Date: 2026-09-30 19:56:55.714643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf1d068f9667'
down_revision: Union[str, Sequence[str], None] = '9ef8866711d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('booking_userid', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'booking_userid')
    # ### end Alembic commands ###
